
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:Welcome1.@db:5432/shopApp

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Welcome1.
      POSTGRES_DB: shopApp
    volumes:
      - ./app/DB/db_data:/var/lib/postgresql/data
      - ./app/DB/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
