FROM python:3.12-slim

WORKDIR /app

# Install dependences
RUN apt-get update && \
    apt-get install -y build-essential && \
    rm -rf /var/lib/apt/lists/*

# copy the python dependences
COPY ./requirements.txt /app/requirements.txt

# intall all the python dependences
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the code
COPY ./src /app/backend/src

# FastAPI port exposed
EXPOSE 8000

ENV PYTHONPATH=/app/backend

# Run the backend
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000"]
