# Usa una imatge base oficial
FROM mcr.microsoft.com/devcontainers/base:ubuntu

# Instal·la Minikube
RUN curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && \
    chmod +x minikube && \
    mv minikube /usr/local/bin/

# Instal·la altres eines si cal
RUN apt-get update && apt-get install -y \
    conntrack \
    socat
